// <auto-generated />
using DecBatch2025MVCCoreProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DecBatch2025MVCCoreProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260114090802_EmpManager")]
    partial class EmpManager
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DecBatch2025MVCCoreProject.Models.Emp", b =>
                {
                    b.Property<int>("eid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("eid"));

                    b.Property<string>("ename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("esalary")
                        .HasColumnType("float");

                    b.Property<int>("mid")
                        .HasColumnType("int");

                    b.HasKey("eid");

                    b.HasIndex("mid");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("DecBatch2025MVCCoreProject.Models.Manager", b =>
                {
                    b.Property<int>("mid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mid"));

                    b.Property<string>("mname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("mid");

                    b.ToTable("mang");
                });

            modelBuilder.Entity("DecBatch2025MVCCoreProject.Models.Emp", b =>
                {
                    b.HasOne("DecBatch2025MVCCoreProject.Models.Manager", "managers")
                        .WithMany("emps")
                        .HasForeignKey("mid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("managers");
                });

            modelBuilder.Entity("DecBatch2025MVCCoreProject.Models.Manager", b =>
                {
                    b.Navigation("emps");
                });
#pragma warning restore 612, 618
        }
    }
}
