// <auto-generated />
using DecBatch2025MVCCoreProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DecBatch2025MVCCoreProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DecBatch2025MVCCoreProject.Models.Account", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("acc");
                });

            modelBuilder.Entity("DecBatch2025MVCCoreProject.Models.Emp", b =>
                {
                    b.Property<int>("eid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("eid"));

                    b.Property<string>("ename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("esalary")
                        .HasColumnType("float");

                    b.Property<int>("mid")
                        .HasColumnType("int");

                    b.HasKey("eid");

                    b.HasIndex("mid");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("DecBatch2025MVCCoreProject.Models.Manager", b =>
                {
                    b.Property<int>("mid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mid"));

                    b.Property<string>("mname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("mid");

                    b.ToTable("mang");
                });

            modelBuilder.Entity("DecBatch2025MVCCoreProject.Models.Student", b =>
                {
                    b.Property<int>("sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sid"));

                    b.Property<string>("scourse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sprofile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sid");

                    b.ToTable("stud");
                });

            modelBuilder.Entity("DecBatch2025MVCCoreProject.Models.Emp", b =>
                {
                    b.HasOne("DecBatch2025MVCCoreProject.Models.Manager", "managers")
                        .WithMany("emps")
                        .HasForeignKey("mid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("managers");
                });

            modelBuilder.Entity("DecBatch2025MVCCoreProject.Models.Manager", b =>
                {
                    b.Navigation("emps");
                });
#pragma warning restore 612, 618
        }
    }
}
